#!/usr/bin/env python3
"""
Cloud Architecture Slide Detector

Analyzes a slide outline (text or JSON) and identifies which slides
need professional architecture diagrams generated by azure-diagrams.

Usage:
    python detect_cloud_arch.py --outline task_plan.md
    python detect_cloud_arch.py --outline slides.json
    python detect_cloud_arch.py --text "Slide 1: Azure AI Architecture\nSlide 2: Benefits"

Output:
    JSON array of slides needing azure-diagrams, each with:
    - slide_index: 0-based slide number
    - slide_title: original slide title/description
    - diagram_type: architecture | process | network | data-pipeline | iot | security
    - suggested_pattern: matching pattern from generate_diagram.py (if any)
    - cloud_services: list of detected cloud service keywords
    - confidence: high | medium
"""

import argparse
import json
import re
import sys
from pathlib import Path


# =============================================================================
# CLOUD SERVICE KEYWORDS (case-insensitive matching)
# =============================================================================

AZURE_SERVICES = {
    # Compute
    "azure vm", "virtual machine", "aks", "kubernetes", "container apps",
    "app service", "function apps", "functions", "azure functions",
    "container instances", "batch", "cloud services",
    # AI/ML
    "azure ai", "ai foundry", "cognitive services", "openai", "azure openai",
    "machine learning", "ml workspace", "ai search", "ai studio",
    "document intelligence", "speech service", "vision",
    # Data
    "cosmos db", "cosmosdb", "azure sql", "sql database", "synapse",
    "data factory", "databricks", "data lake", "data explorer",
    "cache for redis", "redis cache", "postgresql", "mysql",
    # Storage
    "blob storage", "azure storage", "file share", "queue storage",
    "table storage", "data lake storage",
    # Networking
    "virtual network", "vnet", "load balancer", "application gateway",
    "front door", "cdn", "dns", "traffic manager", "expressroute",
    "vpn gateway", "firewall", "private endpoint", "private link",
    "bastion", "nat gateway",
    # Integration
    "api management", "apim", "service bus", "event grid", "event hub",
    "logic apps", "integration account",
    # Security
    "key vault", "azure ad", "entra id", "managed identity",
    "defender", "sentinel", "security center",
    # DevOps
    "azure devops", "container registry", "acr",
    # IoT
    "iot hub", "iot edge", "iot central", "digital twins",
    # Monitor
    "application insights", "log analytics", "monitor", "app insights",
}

AWS_SERVICES = {
    "ec2", "s3", "lambda", "dynamodb", "rds", "sqs", "sns",
    "api gateway", "cloudfront", "ecs", "eks", "fargate",
    "sagemaker", "bedrock", "kinesis", "redshift", "aurora",
    "elasticache", "route 53", "cloudwatch", "iam",
    "step functions", "eventbridge", "vpc",
}

GCP_SERVICES = {
    "compute engine", "gke", "cloud run", "cloud functions",
    "bigquery", "cloud sql", "firestore", "cloud storage",
    "pub/sub", "cloud cdn", "vertex ai", "cloud spanner",
}

ALL_CLOUD_SERVICES = AZURE_SERVICES | AWS_SERVICES | GCP_SERVICES

# Architecture-related keywords
ARCH_KEYWORDS = {
    # English
    "architecture", "topology", "infrastructure", "deployment diagram",
    "network diagram", "data flow", "system design", "service mesh",
    "microservices", "event-driven", "serverless", "hybrid cloud",
    "multi-cloud", "high availability", "disaster recovery",
    "load balancing", "api gateway", "data pipeline", "etl",
    "ci/cd pipeline", "devops pipeline", "integration architecture",
    "security architecture", "reference architecture", "solution architecture",
    "cloud native", "containerization",
    # Chinese
    "架构", "拓扑", "部署", "网络图", "数据流", "系统设计",
    "微服务", "事件驱动", "无服务器", "混合云", "多云",
    "高可用", "灾备", "负载均衡", "数据管道", "集成架构",
    "安全架构", "参考架构", "解决方案架构", "云原生",
}

# Pattern mapping from generate_diagram.py
PATTERN_KEYWORDS = {
    "api-led": ["api management", "apim", "api gateway", "api-led", "三层"],
    "hybrid": ["hybrid", "on-premises", "on-prem", "混合", "本地", "data gateway"],
    "event-driven": ["event-driven", "event grid", "event hub", "pub/sub", "事件驱动"],
    "microservices": ["microservices", "container apps", "service mesh", "微服务", "aks"],
    "b2b-edi": ["b2b", "edi", "trading partner", "integration account"],
    "data-pipeline": ["data pipeline", "data factory", "etl", "elt", "synapse", "databricks", "数据管道"],
    "secure-private": ["private endpoint", "private link", "vnet", "virtual network", "安全", "private"],
    "multi-region": ["multi-region", "geo-redundant", "front door", "disaster recovery", "多区域", "灾备"],
    "iot-streaming": ["iot", "streaming", "real-time", "edge", "物联网", "实时"],
}

# Diagram type classification
DIAGRAM_TYPE_KEYWORDS = {
    "architecture": ["architecture", "架构", "topology", "拓扑", "infrastructure", "部署"],
    "data-pipeline": ["data pipeline", "etl", "elt", "data factory", "数据管道", "数据流"],
    "network": ["network", "vnet", "virtual network", "网络", "topology"],
    "security": ["security", "安全", "private endpoint", "firewall", "key vault"],
    "iot": ["iot", "edge", "streaming", "物联网"],
    "process": ["workflow", "流程", "process", "swimlane", "泳道"],
}


# =============================================================================
# SLIDE PARSING
# =============================================================================

def parse_markdown_outline(text: str) -> list:
    """Parse a markdown task plan or outline into slide entries."""
    slides = []
    lines = text.strip().split("\n")

    # Pattern 1: "Slide N: Title" or "幻灯片 N: Title"
    slide_pattern = re.compile(
        r"(?:slide|幻灯片|s)\s*(\d+)\s*[:：]\s*(.+)",
        re.IGNORECASE
    )

    # Pattern 2: Numbered list "1. Title" or "- Title"
    list_pattern = re.compile(r"^\s*(?:(\d+)[.)]\s+|- |\* )(.*)", re.IGNORECASE)

    # Pattern 3: Markdown headers "## Title" or "### Title"
    header_pattern = re.compile(r"^#{1,4}\s+(?:(?:slide|幻灯片)\s*\d+\s*[:：]\s*)?(.+)", re.IGNORECASE)

    for line in lines:
        line = line.strip()
        if not line:
            continue

        match = slide_pattern.match(line)
        if match:
            slides.append({
                "index": int(match.group(1)) - 1,
                "title": match.group(2).strip()
            })
            continue

        match = list_pattern.match(line)
        if match:
            idx = int(match.group(1)) - 1 if match.group(1) else len(slides)
            title = match.group(2).strip()
            if title and len(title) > 3:  # skip very short items
                slides.append({"index": idx, "title": title})
            continue

        match = header_pattern.match(line)
        if match:
            title = match.group(1).strip()
            if title and len(title) > 3:
                slides.append({"index": len(slides), "title": title})

    # Deduplicate by index, keep last
    seen = {}
    for s in slides:
        seen[s["index"]] = s
    return sorted(seen.values(), key=lambda x: x["index"])


def parse_json_outline(text: str) -> list:
    """Parse a JSON slide outline."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return []

    slides = []
    if isinstance(data, list):
        for i, item in enumerate(data):
            if isinstance(item, str):
                slides.append({"index": i, "title": item})
            elif isinstance(item, dict):
                title = item.get("title", item.get("name", item.get("content", "")))
                slides.append({"index": item.get("index", i), "title": str(title)})
    return slides


# =============================================================================
# DETECTION LOGIC
# =============================================================================

def detect_cloud_content(title: str) -> dict:
    """
    Analyze a slide title/description for cloud architecture content.

    Returns:
        dict with keys: needs_diagram, diagram_type, suggested_pattern,
        cloud_services, confidence
    """
    title_lower = title.lower()

    # Detect cloud services mentioned
    found_services = []
    for service in ALL_CLOUD_SERVICES:
        if service.lower() in title_lower:
            found_services.append(service)

    # Detect architecture keywords
    found_arch = []
    for keyword in ARCH_KEYWORDS:
        if keyword.lower() in title_lower:
            found_arch.append(keyword)

    # Detect best pattern match
    best_pattern = None
    best_pattern_score = 0
    for pattern, keywords in PATTERN_KEYWORDS.items():
        score = sum(1 for kw in keywords if kw.lower() in title_lower)
        if score > best_pattern_score:
            best_pattern_score = score
            best_pattern = pattern

    # Detect diagram type
    detected_type = "architecture"  # default
    best_type_score = 0
    for dtype, keywords in DIAGRAM_TYPE_KEYWORDS.items():
        score = sum(1 for kw in keywords if kw.lower() in title_lower)
        if score > best_type_score:
            best_type_score = score
            detected_type = dtype

    # Decision: needs azure-diagrams?
    has_cloud = len(found_services) > 0
    has_arch = len(found_arch) > 0

    if has_cloud and has_arch:
        confidence = "high"
        needs_diagram = True
    elif has_cloud or (has_arch and best_pattern_score > 0):
        confidence = "medium"
        needs_diagram = True
    else:
        confidence = "low"
        needs_diagram = False

    return {
        "needs_diagram": needs_diagram,
        "diagram_type": detected_type,
        "suggested_pattern": best_pattern,
        "cloud_services": found_services,
        "arch_keywords": found_arch,
        "confidence": confidence,
    }


def analyze_outline(slides: list) -> list:
    """Analyze all slides and return those needing azure-diagrams."""
    results = []
    for slide in slides:
        detection = detect_cloud_content(slide["title"])
        if detection["needs_diagram"]:
            results.append({
                "slide_index": slide["index"],
                "slide_title": slide["title"],
                "diagram_type": detection["diagram_type"],
                "suggested_pattern": detection["suggested_pattern"],
                "cloud_services": detection["cloud_services"],
                "confidence": detection["confidence"],
            })
    return results


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Detect slides that need azure-diagrams for cloud architecture",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --outline task_plan.md
  %(prog)s --outline slides.json
  %(prog)s --text "Slide 1: Azure AI Foundry Architecture\\nSlide 2: Key Benefits"
  %(prog)s --text "1. 系统架构 - Azure Kubernetes + Cosmos DB\\n2. 项目收益"
        """
    )

    parser.add_argument("--outline", "-o", type=str,
                        help="Path to outline file (markdown or JSON)")
    parser.add_argument("--text", "-t", type=str,
                        help="Inline outline text (use \\n for newlines)")
    parser.add_argument("--json", action="store_true",
                        help="Force JSON output (default is human-readable)")

    args = parser.parse_args()

    if not args.outline and not args.text:
        parser.print_help()
        sys.exit(1)

    # Load outline
    if args.outline:
        path = Path(args.outline)
        if not path.exists():
            print(f"Error: File not found: {args.outline}", file=sys.stderr)
            sys.exit(1)
        text = path.read_text(encoding="utf-8")
    else:
        text = args.text.replace("\\n", "\n")

    # Parse
    if text.strip().startswith("[") or text.strip().startswith("{"):
        slides = parse_json_outline(text)
    else:
        slides = parse_markdown_outline(text)

    if not slides:
        print("No slides detected in the outline.", file=sys.stderr)
        print("[]")
        sys.exit(0)

    # Analyze
    results = analyze_outline(slides)

    # Output
    print(json.dumps(results, indent=2, ensure_ascii=False))

    # Summary to stderr
    if results:
        print(f"\n--- Summary ---", file=sys.stderr)
        print(f"Total slides analyzed: {len(slides)}", file=sys.stderr)
        print(f"Slides needing azure-diagrams: {len(results)}", file=sys.stderr)
        for r in results:
            conf = "***" if r["confidence"] == "high" else "**"
            print(f"  [{conf}] Slide {r['slide_index']}: {r['slide_title']}", file=sys.stderr)
            print(f"       Type: {r['diagram_type']}, Pattern: {r['suggested_pattern']}", file=sys.stderr)
            if r["cloud_services"]:
                print(f"       Services: {', '.join(r['cloud_services'])}", file=sys.stderr)
    else:
        print(f"\nNo cloud architecture slides detected. azure-diagrams not needed.", file=sys.stderr)


if __name__ == "__main__":
    main()
